import {
  Announcement,
  OrganizationProfile,
  Member,
  Achievement,
  EventItem,
  GalleryItem,
} from './types';

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-1',
    title: 'Konfirmasi Retret Rohani & Pembinaan Karakter 2026 Telah Dibuka!',
    content:
      'Diberitahukan kepada seluruh siswa Kristen & Katolik SMK Negeri 1 Bantul bahwa konfirmasi kehadiran Retret Rohani 2026 di Wisma Sejahtera Kaliurang dibuka hingga 15 Oktober 2026. Silakan hubungi koordinator siswa / narahubung untuk informasi akomodasi.',
    is_active: true,
    created_at: '2026-09-01T08:00:00Z',
    updated_at: '2026-09-01T08:00:00Z',
  },
  {
    id: 'ann-2',
    title: 'Jadwal Ibadah Jumat Rutin & Latihan Musik Semester Genap',
    content:
      'Ibadah rutin Jumat siang dilaksanakan pukul 11.45 - 13.00 WIB di Ruang Pertemuan 2. Tim musik diharapkan hadir 30 menit lebih awal untuk gladi resik.',
    is_active: false,
    created_at: '2026-08-15T10:00:00Z',
    updated_at: '2026-08-15T10:00:00Z',
  },
];

export const INITIAL_PROFILE: OrganizationProfile = {
  id: 'default',
  name: 'Persekutuan Siswa Kristiani Skansaba',
  school_name: 'SMK Negeri 1 Bantul',
  history:
    'Persekutuan Siswa Kristiani SMK Negeri 1 Bantul (Skansaba) merupakan ruang persekutuan kasih dan keluarga rohani bagi seluruh siswa-siswi beragama Kristen dan Katolik di lingkungan sekolah. Setiap siswa Kristiani secara wajar dan otomatis menjadi bagian dari persekutuan ini, khususnya pada momen peribadatan bersama di sekolah serta peringatan hari raya gerejawi seperti Natal dan Paskah. Tanpa sekat birokrasi formal, persekutuan ini berjalan dengan semangat persaudaraan, saling menopang dalam doa, dan bertumbuh bersama dalam iman dan keteladanan di bawah bimbingan bapak/ibu guru pembina agama.',
  vision:
    'Menjadi persekutuan kasih dan keluarga rohani bagi siswa-siswi Kristen dan Katolik di SMKN 1 Bantul yang saling mendukung dalam doa, berakar dalam firman Tuhan, serta berbuah nyata dalam keteladanan karakter, integritas, dan persaudaraan yang tulus.',
  mission: [
    'Menyelenggarakan persekutuan dan ibadah bersama yang hangat untuk memelihara kehidupan rohani di lingkungan sekolah.',
    'Menjadi ruang persaudaraan di mana setiap siswa Kristen dan Katolik dapat saling mengenal, mendoakan, dan mendukung satu sama lain.',
    'Mempersiapkan perayaan hari besar keagamaan (Natal dan Paskah sekolah) secara gotong royong dan penuh sukacita.',
    'Mengembangkan talenta musik, pujian, dan pelayanan kasih tanpa membebani siswa dengan struktur birokrasi formal.',
    'Menjaga hubungan silaturahmi yang erat antara siswa aktif, para alumni, dan bapak/ibu guru pembina agama.',
  ],
  structure: [
    {
      id: 'str-1',
      role: 'Guru Pembina Agama Kristen & Katolik',
      name: 'Dra. Maria Christine, M.Pd.',
      level: 'pembina',
      photo_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=500&auto=format&fit=crop&q=80',
    },
    {
      id: 'str-2',
      role: 'Koordinator Siswa (Angkatan 2024)',
      name: 'Jonathan Immanuel',
      level: 'inti',
      photo_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=500&auto=format&fit=crop&q=80',
    },
    {
      id: 'str-3',
      role: 'Wakil Koordinator Siswa',
      name: 'Grace Natalia',
      level: 'inti',
      photo_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=500&auto=format&fit=crop&q=80',
    },
    {
      id: 'str-4',
      role: 'Narahubung & Komunikasi',
      name: 'Ruth Deborah Simanjuntak',
      level: 'inti',
      photo_url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=500&auto=format&fit=crop&q=80',
    },
    {
      id: 'str-5',
      role: 'Koordinator Kas Pelayanan',
      name: 'David Christian Wibowo',
      level: 'inti',
      photo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop&q=80',
    },
    {
      id: 'str-6',
      role: 'PIC Ibadah Bersama',
      name: 'Samuel Pratama',
      level: 'divisi',
      division: 'Tim Ibadah & Liturgi',
      photo_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&auto=format&fit=crop&q=80',
    },
    {
      id: 'str-7',
      role: 'PIC Musik & Pujian',
      name: 'Keisha Abigail',
      level: 'divisi',
      division: 'Tim Musik & Pujian',
      photo_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=500&auto=format&fit=crop&q=80',
    },
    {
      id: 'str-8',
      role: 'PIC Persekutuan Doa',
      name: 'Daniel Kristianto',
      level: 'divisi',
      division: 'Tim Doa Bersama',
      photo_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=500&auto=format&fit=crop&q=80',
    },
    {
      id: 'str-9',
      role: 'PIC Dokumentasi & Media',
      name: 'Clara Evelyn',
      level: 'divisi',
      division: 'Tim Dokumentasi & Arsip',
      photo_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80',
    },
  ],
  updated_at: '2026-09-01T00:00:00Z',
};

export const INITIAL_MEMBERS: Member[] = [
  {
    id: 'mem-1',
    name: 'Jonathan Immanuel',
    role: 'Koordinator Siswa (2025/2026)',
    class_year: 2024,
    is_alumni: false,
    photo_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=500&auto=format&fit=crop&q=80',
    contact_info: 'jonathan@skansaba.sch.id',
    instagram: '@jonathan.immanuel',
    created_at: '2024-07-15T08:00:00Z',
  },
  {
    id: 'mem-2',
    name: 'Grace Natalia',
    role: 'Wakil Koordinator Siswa',
    class_year: 2024,
    is_alumni: false,
    photo_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=500&auto=format&fit=crop&q=80',
    contact_info: 'grace.natalia@skansaba.sch.id',
    instagram: '@gracenatalia_',
    created_at: '2024-07-15T08:00:00Z',
  },
  {
    id: 'mem-3',
    name: 'Ruth Deborah Simanjuntak',
    role: 'Narahubung & Komunikasi',
    class_year: 2025,
    is_alumni: false,
    photo_url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=500&auto=format&fit=crop&q=80',
    contact_info: 'ruth.deborah@skansaba.sch.id',
    instagram: '@ruthdeborah',
    created_at: '2025-07-15T08:00:00Z',
  },
  {
    id: 'mem-4',
    name: 'David Christian Wibowo',
    role: 'Koordinator Kas Pelayanan',
    class_year: 2024,
    is_alumni: false,
    photo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop&q=80',
    contact_info: 'david.christian@skansaba.sch.id',
    instagram: '@davidchristianw',
    created_at: '2024-07-15T08:00:00Z',
  },
  {
    id: 'mem-5',
    name: 'Samuel Pratama',
    role: 'PIC Ibadah Bersama',
    class_year: 2025,
    is_alumni: false,
    photo_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&auto=format&fit=crop&q=80',
    contact_info: 'samuel.p@skansaba.sch.id',
    instagram: '@samuelpratama_',
    created_at: '2025-07-15T08:00:00Z',
  },
  {
    id: 'mem-6',
    name: 'Keisha Abigail',
    role: 'PIC Musik & Pujian',
    class_year: 2025,
    is_alumni: false,
    photo_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=500&auto=format&fit=crop&q=80',
    contact_info: 'keisha.abigail@skansaba.sch.id',
    instagram: '@keishaabigail',
    created_at: '2025-07-15T08:00:00Z',
  },
  {
    id: 'mem-7',
    name: 'Daniel Kristianto',
    role: 'PIC Persekutuan Doa',
    class_year: 2026,
    is_alumni: false,
    photo_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=500&auto=format&fit=crop&q=80',
    contact_info: 'daniel.k@skansaba.sch.id',
    instagram: '@danielkristianto',
    created_at: '2026-07-15T08:00:00Z',
  },
  {
    id: 'mem-8',
    name: 'Clara Evelyn',
    role: 'PIC Dokumentasi & Media',
    class_year: 2026,
    is_alumni: false,
    photo_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80',
    contact_info: 'clara.evelyn@skansaba.sch.id',
    instagram: '@clara.evelyn',
    created_at: '2026-07-15T08:00:00Z',
  },
  {
    id: 'mem-9',
    name: 'Michael Aditya Nugroho',
    role: 'Alumni (Angkatan 2023)',
    class_year: 2023,
    is_alumni: true,
    photo_url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=500&auto=format&fit=crop&q=80',
    contact_info: 'michael.aditya@alumni.skansaba.id',
    instagram: '@michaeladityan',
    created_at: '2023-07-15T08:00:00Z',
  },
  {
    id: 'mem-10',
    name: 'Priskila Sarah Santoso',
    role: 'Alumni (Angkatan 2023)',
    class_year: 2023,
    is_alumni: true,
    photo_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=500&auto=format&fit=crop&q=80',
    contact_info: 'priskila.sarah@alumni.skansaba.id',
    instagram: '@priskilasarah',
    created_at: '2023-07-15T08:00:00Z',
  },
  {
    id: 'mem-11',
    name: 'Gabriel Ezra Permana',
    role: 'Alumni (Angkatan 2022)',
    class_year: 2022,
    is_alumni: true,
    photo_url: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=500&auto=format&fit=crop&q=80',
    contact_info: 'gabriel.ezra@alumni.skansaba.id',
    instagram: '@gabrielezra',
    created_at: '2022-07-15T08:00:00Z',
  },
];

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach-1',
    title: 'Juara 1 Lomba Vokal Solo Rohani Remaja',
    recipient_name: 'Keisha Abigail',
    member_id: 'mem-6',
    level: 'Kabupaten',
    year: 2025,
    certificate_url: 'https://images.unsplash.com/photo-1578269174936-2709b6aeb913?w=800&auto=format&fit=crop&q=80',
    description: 'Meraih peringkat pertama dalam kompetisi bernyanyi solo rohani se-Kabupaten Bantul dalam rangka Festival Seni Remaja Gerejawi 2025.',
    created_at: '2025-11-20T10:00:00Z',
  },
  {
    id: 'ach-2',
    title: 'Juara 2 Cerdas Cermat Alkitab (CCA) Pelajar',
    recipient_name: 'Jonathan Immanuel & Tim Skansaba',
    member_id: 'mem-1',
    level: 'Provinsi',
    year: 2025,
    certificate_url: 'https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?w=800&auto=format&fit=crop&q=80',
    description: 'Berhasil mengungguli perwakilan SMA/SMK se-D.I. Yogyakarta dalam perlombaan pemahaman Alkitab dan teologi remaja tingkat provinsi.',
    created_at: '2025-08-14T09:30:00Z',
  },
  {
    id: 'ach-3',
    title: 'Juara 1 Lomba Desain Poster Rohani Digital',
    recipient_name: 'Clara Evelyn',
    member_id: 'mem-8',
    level: 'Sekolah',
    year: 2025,
    certificate_url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop&q=80',
    description: 'Karya poster bertema "Kasih yang Memulihkan di Tengah Generasi Digital" meraih penghargaan desain terbaik pada Bulan Bahasa & Seni Skansaba.',
    created_at: '2025-10-28T14:00:00Z',
  },
  {
    id: 'ach-4',
    title: 'Juara 3 Paduan Suara Antar SMA/SMK DIY',
    recipient_name: 'Tim Paduan Suara Kristiani Skansaba',
    level: 'Provinsi',
    year: 2024,
    certificate_url: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop&q=80',
    description: 'Membawakan lagu "Amazing Grace" dan "Kidung Agung" dengan harmoni 4 suara pada Temu Raya Remaja Kristiani DIY.',
    created_at: '2024-12-10T11:00:00Z',
  },
  {
    id: 'ach-5',
    title: 'Finalis Terpilih Duta Karakter Kristiani Pelajar Nasional',
    recipient_name: 'Grace Natalia',
    member_id: 'mem-2',
    level: 'Nasional',
    year: 2024,
    certificate_url: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&auto=format&fit=crop&q=80',
    description: 'Mewakili sekolah dan daerah dalam program pembinaan integritas dan kepemimpinan generasi muda di Jakarta.',
    created_at: '2024-09-05T08:00:00Z',
  },
];

export const INITIAL_EVENTS: EventItem[] = [
  {
    id: 'ev-1',
    title: 'Retret Rohani & Pembinaan Karakter 2026',
    slug: 'retret-rohani-pembinaan-karakter-2026',
    event_date: '2026-10-24',
    time: '08.00 WIB - Selesai',
    location: 'Wisma Sejahtera Kaliurang, Sleman, D.I. Yogyakarta',
    status: 'upcoming',
    summary:
      'Retret tahunan tiga hari dua malam bagi seluruh siswa Kristiani Skansaba untuk mempererat iman, persekutuan, dan kepemimpinan.',
    description:
      'Retret Rohani & Pembinaan Karakter 2026 mengusung tema "Berakar, Bertumbuh, dan Berdampak" (Kolose 2:6-7). Acara ini dirancang sebagai momen jeda dari rutinitas sekolah untuk mendekatkan diri kepada Tuhan, mengevaluasi perjalanan hidup, serta membangun kebersamaan yang hangat antar angkatan. Kegiatan mencakup sesi firman inspiratif, malam pujian dan penyembahan (Praise & Worship Night), outbound kebersamaan di lereng Merapi, serta kelompok diskusi pembinaan karakter.',
    cover_image_url:
      'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=1000&auto=format&fit=crop&q=80',
    gallery_urls: [
      'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1528605248644-14dd04022da1?w=800&auto=format&fit=crop&q=80',
    ],
    created_at: '2026-08-01T10:00:00Z',
  },
  {
    id: 'ev-2',
    title: 'Ibadah Padang & Perayaan Paskah Pelajar 2026',
    slug: 'ibadah-padang-paskah-pelajar-2026',
    event_date: '2026-11-14',
    time: '07.30 - 14.00 WIB',
    location: 'Area Terbuka Taman Wisata Dolan Deso Boro, Kulon Progo',
    status: 'upcoming',
    summary:
      'Ibadah syukur bersama di alam terbuka dengan sukacita kebangkitan Kristus, games kekeluargaan, dan makan siang bersama.',
    description:
      'Ibadah Padang mengajak seluruh siswa dan guru pembina menikmati keindahan alam ciptaan sembari mengucap syukur atas karya keselamatan. Dilengkapi dengan games persahabatan, perlombaan cari telur paskah rohani, dan perenungan firman yang menyegarkan jiwa.',
    cover_image_url:
      'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=1000&auto=format&fit=crop&q=80',
    gallery_urls: [
      'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?w=800&auto=format&fit=crop&q=80',
    ],
    created_at: '2026-08-10T10:00:00Z',
  },
  {
    id: 'ev-3',
    title: 'Aksi Kasih & Bakti Sosial Panti Asuhan Kasih Bunda',
    slug: 'aksi-kasih-bakti-sosial-2026',
    event_date: '2026-12-05',
    time: '09.00 - 13.00 WIB',
    location: 'Panti Asuhan Kasih Bunda, Sewon, Bantul',
    status: 'upcoming',
    summary:
      'Penyaluran bantuan sembako, perlengkapan belajar, dan bernyanyi bersama adik-adik panti asuhan.',
    description:
      'Sebagai wujud nyata kasih Kristus yang melayani sesama, persekutuan siswa Kristiani mengumpulkan donasi sukarela berupa buku, alat tulis, pakaian layak pakai, dan paket sembako untuk disalurkan ke panti asuhan mitra.',
    cover_image_url:
      'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=1000&auto=format&fit=crop&q=80',
    gallery_urls: [
      'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=800&auto=format&fit=crop&q=80',
    ],
    created_at: '2026-08-15T10:00:00Z',
  },
  {
    id: 'ev-4',
    title: 'Ibadah & Perayaan Natal Skansaba 2025',
    slug: 'ibadah-perayaan-natal-skansaba-2025',
    event_date: '2025-12-19',
    time: '08.30 - 12.30 WIB',
    location: 'Aula Utama SMK Negeri 1 Bantul',
    status: 'completed',
    summary:
      'Peringatan kelahiran Kristus dengan tema "Terang di Tengah Dunia", dihadiri oleh seluruh siswa, alumni, dan dewan guru.',
    description:
      'Ibadah dan perayaan Natal berlangsung dengan penuh khidmat dan sukacita. Ditampilkan drama musikal kelahiran Yesus, penampilan vokal grup persembahan siswa kelas X, XI, dan XII, serta renungan natal oleh Pdt. Stefanus dari Bantul. Momen penyalaan lilin natal menjadi puncak keharuan yang memperkuat tali persaudaraan keluarga besar Kristiani Skansaba.',
    cover_image_url:
      'https://images.unsplash.com/photo-1543258103-a62bdc069871?w=1000&auto=format&fit=crop&q=80',
    gallery_urls: [
      'https://images.unsplash.com/photo-1543258103-a62bdc069871?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1512474932049-78ac69ede12c?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1576919228236-a097c32a5cd4?w=800&auto=format&fit=crop&q=80',
    ],
    created_at: '2025-12-01T09:00:00Z',
  },
  {
    id: 'ev-5',
    title: 'Pembekalan & Temu Keakraban Siswa Kristiani 2025',
    slug: 'pembekalan-temu-keakraban-siswa-kristiani-2025',
    event_date: '2025-10-11',
    time: '08.00 - 16.00 WIB',
    location: 'Laboratorium Pembelajaran Skansaba',
    status: 'completed',
    summary:
      'Sesi pembekalan kebersamaan, pengenalan talenta pelayanan, dan kepemimpinan kasih persaudaraan (Servant Leadership).',
    description:
      'Pertemuan keakraban bagi siswa-siswi Kristen dan Katolik untuk saling mengenal antartingkat kelas, berbagi pengalaman pelayanan ibadah bersama, serta merancang kebersamaan Natal dan Paskah secara bersahaja.',
    cover_image_url:
      'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=1000&auto=format&fit=crop&q=80',
    gallery_urls: [
      'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1531497865144-0464ef8fb9a9?w=800&auto=format&fit=crop&q=80',
    ],
    created_at: '2025-09-20T10:00:00Z',
  },
];

export const INITIAL_GALLERY: GalleryItem[] = [
  {
    id: 'gal-1',
    title: 'Penyalaan Lilin Malam Natal Skansaba',
    event_name: 'Perayaan Natal 2025',
    year: 2025,
    image_url: 'https://images.unsplash.com/photo-1512474932049-78ac69ede12c?w=1000&auto=format&fit=crop&q=80',
    description: 'Momen hening penyalaan lilin syahdu diiringi lagu Malam Kudus bersama para siswa dan guru pembina.',
    created_at: '2025-12-19T12:00:00Z',
  },
  {
    id: 'gal-2',
    title: 'Penampilan Vokal Solo Keisha Abigail',
    event_name: 'Festival Seni Remaja Gerejawi 2025',
    year: 2025,
    image_url: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=1000&auto=format&fit=crop&q=80',
    description: 'Penampilan memukau di babak final vokal solo rohani se-Kabupaten Bantul.',
    created_at: '2025-11-20T14:00:00Z',
  },
  {
    id: 'gal-3',
    title: 'Kebersamaan Sesi Outbound Kaliurang',
    event_name: 'Retret Rohani 2025',
    year: 2025,
    image_url: 'https://images.unsplash.com/photo-1528605248644-14dd04022da1?w=1000&auto=format&fit=crop&q=80',
    description: 'Keceriaan dan keakraban lintas angkatan saat permainan team building di kaki gunung Merapi.',
    created_at: '2025-10-15T11:00:00Z',
  },
  {
    id: 'gal-4',
    title: 'Ibadah Persekutuan Doa Jumat Siang',
    event_name: 'Ibadah Rutin Mingguan',
    year: 2026,
    image_url: 'https://images.unsplash.com/photo-1438232992991-995b7058bbb3?w=1000&auto=format&fit=crop&q=80',
    description: 'Suasana khusyuk doa bersama dan pembacaan renungan Alkitab harian.',
    created_at: '2026-02-13T12:30:00Z',
  },
  {
    id: 'gal-5',
    title: 'Penyerahan Piala Juara Cerdas Cermat Alkitab',
    event_name: 'Temu Pelajar Kristiani DIY',
    year: 2025,
    image_url: 'https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?w=1000&auto=format&fit=crop&q=80',
    description: 'Tim Skansaba berfoto bersama piala penghargaan tingkat provinsi.',
    created_at: '2025-08-14T15:00:00Z',
  },
  {
    id: 'gal-6',
    title: 'Foto Bersama Pengurus dan Guru Pembina',
    event_name: 'Serah Terima Jabatan Pengurus',
    year: 2025,
    image_url: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=1000&auto=format&fit=crop&q=80',
    description: 'Pelantikan kepengurusan masa bakti 2025/2026 di hadapan dewan pembina sekolah.',
    created_at: '2025-07-20T10:00:00Z',
  },
];
